[package]
name = "span-inspector"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib = { workspace = true, features = ["full"] }
cxx-qt-macro = { workspace = true }
cxx-qt-gen = { workspace = true }
proc-macro2.workspace = true
prettyplease = { version = "0.2", features = ["verbatim"] }
syn.workspace=true

[build-dependencies]
cxx-qt-build = { workspace = true, features = [ "link_qt_object_files" ] }

[lints]
workspace = true
