# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-FileContributor: Ben Ford <ben.ford@kdab.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

coverage:
  status:
    project:
      default:
        target: 95%
    patch: true


ignore:
  - "./tests/" # This got included for some reason in either build or test and is not relevant to unit tests
