// SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
// SPDX-FileContributor: Leon Matthes <leon.matthes@kdab.com>
//
// SPDX-License-Identifier: MIT OR Apache-2.0

//! This modules contains utilities for building crates that use cxx-qt-build.

#[doc(hidden)]
// This struct should not be used directly.
// Only use the Manifests generated by cxx-qt-build.
pub struct Manifest {
    pub name: String,
    pub qt_modules: Vec<String>,
    pub defines: Vec<String>,
    pub initializers: Vec<String>,
}
