// clang-format off
// SPDX-FileCopyrightText: 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
// clang-format on
// SPDX-FileContributor: Darshan Phaldesai <dev.darshanphaldesai@gmail.com>
//
// SPDX-License-Identifier: MIT OR Apache-2.0
#pragma once

// The definitions file is auto-generated by the build script
#include <cxx-qt-lib/definitions.h>

#ifdef CXX_QT_QML_FEATURE

#include <QtQml/QQmlImageProviderBase>

namespace rust {
namespace cxxqtlib1 {

using QQmlImageProviderBaseImageType = QQmlImageProviderBase::ImageType;

}
}

#endif
