// clang-format off
// SPDX-FileCopyrightText: 2022 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
// clang-format on
// SPDX-FileContributor: Andrew Hayzen <andrew.hayzen@kdab.com>
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
//
#pragma once

// The definitions file is auto-generated by the build script
#include <cxx-qt-lib/definitions.h>

#include "qvector_QByteArray.h"
#include "qvector_bool.h"
#include "qvector_f32.h"
#include "qvector_f64.h"
#include "qvector_i16.h"
#include "qvector_i32.h"
#include "qvector_i64.h"
#include "qvector_i8.h"
#ifdef CXX_QT_GUI_FEATURE
#include "qvector_QColor.h"
#endif
#include "qvector_QDate.h"
#include "qvector_QDateTime.h"
#include "qvector_QLine.h"
#include "qvector_QLineF.h"
#include "qvector_QMargins.h"
#include "qvector_QMarginsF.h"
#include "qvector_QPersistentModelIndex.h"
#include "qvector_QPoint.h"
#include "qvector_QPointF.h"
#include "qvector_QRect.h"
#include "qvector_QRectF.h"
#include "qvector_QSize.h"
#include "qvector_QSizeF.h"
#include "qvector_QString.h"
#include "qvector_QTime.h"
#include "qvector_QUrl.h"
#include "qvector_QUuid.h"
#include "qvector_QVariant.h"
#include "qvector_u16.h"
#include "qvector_u32.h"
#include "qvector_u64.h"
#include "qvector_u8.h"
