// SPDX-FileCopyrightText: 2021 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
// SPDX-FileContributor: Andrew Hayzen <andrew.hayzen@kdab.com>
// SPDX-FileContributor: Gerhard de Clercq <gerhard.declercq@kdab.com>
//
// SPDX-License-Identifier: MIT OR Apache-2.0

// TODO: This should be auto-generated by cxx-qt-build in the build script
pub fn cxx_qt_build_manifest() -> cxx_qt::build::Manifest {
    cxx_qt::build::Manifest {
        name: "cxx-qt-lib".to_owned(),
        qt_modules: vec![
            #[cfg(feature = "qt_gui")]
            "Gui".to_owned(),
            #[cfg(feature = "qt_qml")]
            "Qml".to_owned(),
            #[cfg(feature = "qt_quickcontrols")]
            "QuickControls2".to_owned(),
        ],
        defines: vec![
            #[cfg(feature = "qt_gui")]
            "CXX_QT_GUI_FEATURE".to_owned(),
            #[cfg(feature = "qt_qml")]
            "CXX_QT_QML_FEATURE".to_owned(),
            #[cfg(feature = "qt_quickcontrols")]
            "CXX_QT_QUICKCONTROLS_FEATURE".to_owned(),
        ],
        initializers: vec![
            include_str!("core/init.cpp").to_owned(),
            #[cfg(feature = "qt_gui")]
            include_str!("gui/init.cpp").to_owned(),
        ],
    }
}

#[cfg(not(any(cxxqt_qt_version_major = "5", cxxqt_qt_version_major = "6")))]
compile_error!("cxxqt_qt_version_major must be either \"5\" or \"6\"");

mod core;

pub use crate::core::*;

#[cfg(feature = "qt_gui")]
mod gui;
#[cfg(feature = "qt_gui")]
pub use crate::gui::*;

#[cfg(feature = "qt_qml")]
mod qml;
#[cfg(feature = "qt_qml")]
pub use crate::qml::*;

#[cfg(feature = "qt_quickcontrols")]
mod quickcontrols;
#[cfg(feature = "qt_quickcontrols")]
pub use crate::quickcontrols::*;
